name: explore
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  easy_dynamic_theme: ^2.0.0
  flutter_tex: 
  firebase_core: ^1.0.2
  get :

  firebase_auth: 
  firebase_auth_web :
  google_sign_in: ^5.0.1
  url_launcher: ^6.0.9
  flutter_auth_buttons: ^0.10.0
  outlined_text: ^1.0.0
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_downloader: ^1.4.4
  video_player: ^2.3.0
  lite_rolling_switch: ^0.1.1
  international_phone_input: 
  flutter_svg: ^1.0.3
  custom_switch: ^0.0.1
  apple_sign_in: ^0.1.0
  geolocator: ^8.2.1
  glassmorphism: ^3.0.0
  getwidget: ^2.0.3
  pluto_menu_bar: ^0.1.4
  path_provider :
  cookie_jar :
  dio :
  provider : ^6.0.3
  device_preview :



  
  auto_size_text: 
  fluttertoast:
  geocoding:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf

    
    - family: SanFranciscos
      fonts:

        - asset: fonts/otf/SFUIText-Regular.otf


    - family: SanFrancisco
      fonts:

        - asset: fonts/otf/SFNSDisplay-Thin.otf

    - family: SanFranc
      fonts:      
        - asset: fonts/otf/SFNSDisplay-Black.otf

    - family: SanFran
      fonts:     
       
        - asset: fonts/otf/SFNSDisplay-Light.otf
        
       
       

  assets:
    - assets/
    - assets/icons/
    
    